sudo: false
language: python

python:
  - 3.6
  - 3.5
  - 3.4
  - 3.3
  - 2.7
  - 2.6
  - pypy

env:
  - TOXENV=py,codecov

matrix:
  include:
    - python: nightly
      env: TOXENV=py
    - python: 3.6
      env: TOXENV=docs-html

before_install:
  - mkdir -p $HOME/bin
  - curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | tar -zxvf- -C $HOME/bin
  - testspace config url $TS_ORG.testspace.com

install:
  - pip install tox

script:
  - if [[ "${TOXENV}" =~ ^py ]] ; then
      tox -- --junit-xml=testresults.xml;
    else
      tox;
    fi

after_script:
  - if [[ "${TOXENV}" =~ ^py ]] ; then
      testspace [python_${TRAVIS_PYTHON_VERSION}]testresults.xml{tests};
    fi
 
cache:
  - pip

branches:
  only:
    - master
    - add-test-reporting
    - /^.*-maintenance$/

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#pocoo"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
